### ISSUE TITLE
mix deps.audit fails on git dependencies.

### ISSUE THREAD

**Issue by aselder** [mirego/mix_audit#1]
```
** (FunctionClauseError) no function clause matching in MixAudit.Project.map_dependency/2    
    
    The following arguments were given to MixAudit.Project.map_dependency/2:
    
        # 1
        {:git, "https://github.com/bitwalker/distillery.git", "6700edb017804e51aec14dedb8df888d1db4e63c", [ref: "6700edb017804e51aec14dedb8df888d1db4e63c"]}
    
        # 2
        "/Users/andrew/Development/ecom_api/mix.lock"
    
    Attempted function clauses (showing 2 out of 2):
    
        defp map_dependency({_, package, version, _, _, _, _}, lockfile)
        defp map_dependency({_, package, version, _, _, _, _, _}, lockfile)
    
    lib/mix_audit/project.ex:30: MixAudit.Project.map_dependency/2
    (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
    (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
    (elixir) lib/enum.ex:2994: Enum.flat_map_list/2
    lib/mix_audit/cli/audit.ex:18: MixAudit.CLI.Audit.run/1
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
```

**Comment by aselder** [comment]
Here's the declaration from the `mix.exs` file:

```
      {:distillery,
       github: "bitwalker/distillery",
       ref: "6700edb017804e51aec14dedb8df888d1db4e63c",
       override: true},
```

**Comment by remi** [comment]
Hi Andrew,

Good catch! I’m going to restrict the parsing to `:hex` dependencies only.

**Comment by remi** [comment]
I just pushed [1.0.2](https://hex.pm/packages/mix_audit/0.1.2) with a fix for this issue.

Thanks again!
